services:
    db:
        container_name: posthog_db
        environment:
            POSTGRES_DB: posthog
            POSTGRES_PASSWORD: posthog
            POSTGRES_USER: posthog
        image: postgres:13-alpine
        volumes:
            - postgres-data:/var/lib/postgresql/data
    redis:
        container_name: posthog_redis
        image: redis:6.2.7-alpine
        command: redis-server --maxmemory-policy allkeys-lru --maxmemory 200mb
    clickhouse:
        #
        # Note: please keep the default version in sync across
        #       `posthog` and the `charts-clickhouse` repos
        #
        image: yandex/clickhouse-server:${CLICKHOUSE_SERVER_IMAGE_VERSION:-21.6.5.37}
        depends_on:
            - kafka
            - zookeeper
        ports:
            - '8123:8123'
            - '9000:9000'
            - '9440:9440'
            - '9009:9009'
        volumes:
            - ./ee/idl:/idl
            - ./docker/clickhouse/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
            - ./docker/clickhouse/config.xml:/etc/clickhouse-server/config.xml
            - ./docker/clickhouse/users.xml:/etc/clickhouse-server/users.xml
    pgadmin: 
        image: dpage/pgadmin4
        ports:
            - '8081:5050'
        environment:
            PGADMIN_LISTEN_PORT: 5050
            PGADMIN_DEFAULT_EMAIL: admin@gmail.com
            PGADMIN_DEFAULT_PASSWORD: averysecretkey
    zookeeper:
        image: zookeeper:3.7.0
    kafka:
        image: bitnami/kafka:2.8.1-debian-10-r99
        depends_on:
            - zookeeper
        ports:
            - '9092:9092'
        environment:
            KAFKA_BROKER_ID: 1001
            KAFKA_CFG_RESERVED_BROKER_MAX_ID: 1001
            KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
            KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
            KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
            ALLOW_PLAINTEXT_LISTENER: 'true'

    web:
        restart: always
        container_name: posthog_web
        depends_on:
            - db
            - redis
            - clickhouse
            - kafka
        environment:
            DATABASE_URL: postgres://posthog:posthog@db:5432/posthog
            REDIS_URL: redis://redis:6379/
            KAFKA_URL: 'kafka://kafka'
            KAFKA_HOSTS: 'kafka:9092'
            CLICKHOUSE_HOST: 'clickhouse'
            DISABLE_SECURE_SSL_REDIRECT: 'true'
            CLICKHOUSE_DATABASE: 'posthog'
            CLICKHOUSE_SECURE: 'false'
            CLICKHOUSE_VERIFY: 'false'
            SECRET_KEY: thisisaverysecretkey
            PGHOST: db
            PGUSER: posthog
            PGPASSWORD: posthog
        image: posthog/posthog:latest
        ports:
            - 8000:8000
            - 8080:8000
volumes:
    postgres-data:
version: '3'
